version: '3'

services:
  database:
    container_name: mysql-db-container
    image: mysql/mysql-server:8.0.32
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lezhin
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - local-network

networks:
  local-network: